name: Send RCON commands
description: Send command(s) via RCON connection to a RCON server
icon: arrow-right-circle
color: green
inputs:
  server:
    required: true
    description: The server IP address
  port:
    required: false
    description: The server's RCON port
    default: 25575
  password:
    required: false
    description: The RCON password to authenticate
    default: ""
  commands:
    required: true
    description: Additional commands to send
  send-push-info:
    required: false
    description: Sends information about the push to the server as a tellraw
    default: true
  push-info-recipient:
    required: false
    description: Changes the selector of who should be getting the server info.
    default: "@a"
runs:
  using: node12
  main: index.js
